// Generated by scripts/build-brand.mjs from the design-system submodule.
// Do not edit by hand. Run `npm run tokens` after bumping the submodule.

/** The Dev Labs brand primitives Almanac uses. */
export const BRAND = {
  /** Flask orange. Heat ramp, bars, the streak flame. */
  accent: "#f47c20",
  /** Darker orange, for accent-as-text where the surface may be light. */
  accentStrong: "#d9660c",
  accentSoft: "#fdebdc",
  /** Near-black. Text on an accent fill, in either theme. */
  ink: "#0e0e10",
  paper: "#f4f3f1",
  grey: "#3c3c40",
  fontDisplay: "'Space Grotesk Variable', ui-sans-serif, sans-serif",
  fontMono: "'IBM Plex Mono', ui-monospace, monospace",
  displayWeight: 600,
  displayTracking: "-0.02em",
  monoTracking: "0.02em",
  radius: {
    sm: "4px",
    md: "8px",
    lg: "14px",
    full: "9999px",
  },
  space: {
    xxs: "4px",
    xs: "8px",
    sm: "12px",
    md: "16px",
    lg: "24px",
  },
} as const;

/** Font files shipped in media/fonts, loaded through webview URIs. */
export const BRAND_FONT_FILES = {
  display: "space-grotesk-variable.woff2",
  mono400: "ibm-plex-mono-400.woff2",
  mono600: "ibm-plex-mono-600.woff2",
} as const;
