// Generates src/ui/brand.ts from the design-system submodule, and copies the
// brand webfonts into media/fonts/.
//
// The submodule is the source of truth, exactly as it is for the website,
// learning portal and community apps. Generating rather than hand-copying is
// what stops Almanac's palette drifting from the other three: bump the
// submodule, run `npm run tokens`, and any change shows up as a diff.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tokensFile = path.join(root, "design-system", "design-tokens.json");

const FONT_SOURCES = [
  {
    from: "@fontsource-variable/space-grotesk/files/space-grotesk-latin-wght-normal.woff2",
    to: "space-grotesk-variable.woff2",
  },
  {
    from: "@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2",
    to: "ibm-plex-mono-400.woff2",
  },
  {
    from: "@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-600-normal.woff2",
    to: "ibm-plex-mono-600.woff2",
  },
];

function value(node, ...keys) {
  let current = node;
  for (const key of keys) {
    current = current?.[key];
  }
  if (current?.$value === undefined) {
    throw new Error(`design token ${keys.join(".")} is missing from design-tokens.json`);
  }
  return current.$value;
}

async function readTokens() {
  try {
    return JSON.parse(await fs.readFile(tokensFile, "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new Error(
        "design-system/design-tokens.json not found. Run `git submodule update --init` first."
      );
    }
    throw error;
  }
}

async function copyFonts() {
  const target = path.join(root, "media", "fonts");
  await fs.mkdir(target, { recursive: true });
  for (const font of FONT_SOURCES) {
    const source = path.join(root, "node_modules", font.from);
    await fs.copyFile(source, path.join(target, font.to));
  }
  return FONT_SOURCES.map((font) => font.to);
}

const tokens = await readTokens();

const brand = {
  accent: value(tokens.color, "accent"),
  accentStrong: value(tokens.color, "accentStrong"),
  accentSoft: value(tokens.color, "accentSoft"),
  ink: value(tokens.color, "ink"),
  paper: value(tokens.color, "paper"),
  grey: value(tokens.color, "grey"),
  fontDisplay: value(tokens.fontFamily, "display"),
  fontMono: value(tokens.fontFamily, "mono"),
  displayWeight: value(tokens.typography, "displayWeight"),
  displayTracking: value(tokens.typography, "displayTracking"),
  monoTracking: value(tokens.typography, "monoTracking"),
  radius: {
    sm: value(tokens.radius, "sm"),
    md: value(tokens.radius, "md"),
    lg: value(tokens.radius, "lg"),
    full: value(tokens.radius, "full"),
  },
  space: {
    xxs: value(tokens.space, "xxs"),
    xs: value(tokens.space, "xs"),
    sm: value(tokens.space, "sm"),
    md: value(tokens.space, "md"),
    lg: value(tokens.space, "lg"),
  },
};

const quoteStack = (stack) => stack.map((family) => (family.includes(" ") ? `'${family}'` : family)).join(", ");

const output = `// Generated by scripts/build-brand.mjs from the design-system submodule.
// Do not edit by hand. Run \`npm run tokens\` after bumping the submodule.

/** The Dev Labs brand primitives Almanac uses. */
export const BRAND = {
  /** Flask orange. Heat ramp, bars, the streak flame. */
  accent: "${brand.accent}",
  /** Darker orange, for accent-as-text where the surface may be light. */
  accentStrong: "${brand.accentStrong}",
  accentSoft: "${brand.accentSoft}",
  /** Near-black. Text on an accent fill, in either theme. */
  ink: "${brand.ink}",
  paper: "${brand.paper}",
  grey: "${brand.grey}",
  fontDisplay: "${quoteStack(brand.fontDisplay)}",
  fontMono: "${quoteStack(brand.fontMono)}",
  displayWeight: ${brand.displayWeight},
  displayTracking: "${brand.displayTracking}",
  monoTracking: "${brand.monoTracking}",
  radius: {
    sm: "${brand.radius.sm}",
    md: "${brand.radius.md}",
    lg: "${brand.radius.lg}",
    full: "${brand.radius.full}",
  },
  space: {
    xxs: "${brand.space.xxs}",
    xs: "${brand.space.xs}",
    sm: "${brand.space.sm}",
    md: "${brand.space.md}",
    lg: "${brand.space.lg}",
  },
} as const;

/** Font files shipped in media/fonts, loaded through webview URIs. */
export const BRAND_FONT_FILES = {
  display: "space-grotesk-variable.woff2",
  mono400: "ibm-plex-mono-400.woff2",
  mono600: "ibm-plex-mono-600.woff2",
} as const;
`;

await fs.writeFile(path.join(root, "src", "ui", "brand.ts"), output, "utf8");
const fonts = await copyFonts();

console.log(`brand tokens written from design-system @ ${tokens.$description ? "design-tokens.json" : "?"}`);
console.log(`  accent ${brand.accent}, display ${quoteStack(brand.fontDisplay)}`);
console.log(`  fonts copied: ${fonts.join(", ")}`);
